export const GET_DATA_PRODUCT = 'GET_DATA_PRODUCT';
export const GET_DATA_CUSTOMERS = 'GET_DATA_CUSTOMERS';
export const GET_USER_LOGIN = 'GET_USER_LOGIN';

export const FETCH_DATA_PRODUCT_SUCCESS = 'FETCH_DATA_PRODUCT_SUCCESS';
export const FETCH_DATA_PRODUCT_FALID = 'FETCH_DATA_PRODUCT_FALID';
export const FETCH_DATA_CUSTOMERS_SUCCESS = 'FETCH_DATA_CUSTOMERS_SUCCESS';
export const FETCH_DATA_CUSTOMERS_FAILD = 'FETCH_DATA_CUSTOMERS_FAILD';
export const FETCH_DATA_USER_LOGIN_SUCCESS = 'FETCH_DATA_USER_LONGIN_SUCCESS';
export const FETCH_DATA_USER_LOGIN_FAILD = 'FETCH_DATA_USER_LOGIN_FAILD';